# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f776a1bc28aac20639d94e4c460240d237e9d8c5fc3c3dcb2be007fa5ad00b58e1394bf335389b70601a64147620aef65c06d5d332bf229f342a9dc6c3381748

test:
  secret_key_base: 8026063f3c7dbe35ba1cf9a8caf40d874253a8c1c3ac1dc020b6fbb7512aa9966b57dc68814135050a06c405821f26892b1c67bba870e5592642df3fb2b7f825

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
